controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


users:
    path: /users
    controller: App\Controller\UserController::test
    methods: [GET]