controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


register:
    path: /user/register
    controller: App\Controller\UserLoginController::register
    methods: ['POST']

api_login_check:
    path: /api/login_check